/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"

#define APB1_CLK 16000000U
#define USART_BAUDRATE 115200

void uart_write(int ch);

int __io_putchar(int ch)
{
    uart_write(ch);
    return ch;
}

int main(void)
{
    pRCC->AHB1ENR |= (1 << 3); // turn on peripheral clock for GPIO port D

    pGPIOD->MODER |= (0b10 << 16); // set GPIOD pin 8 to alternate function mode
    pGPIOD->AFRH |= (0b0111 << 0); // set GPIOD pin 8 as USART3_TX (AF7 according to datasheet)

    pRCC->APB1ENR |= (1 << 18); // enable USART3 clock

    pUSART3->BRR |= (APB1_CLK + USART_BAUDRATE / 2) / USART_BAUDRATE; // set baud rate of USART3
    pUSART3->CR1 |= (1 << 3);                                         // enable USART3 transmit
    pUSART3->CR1 |= (1 << 13);                                        // enable USART3

    while (1)
    {
        printf("Hello World\n\r");
    }
}

void uart_write(int ch)
{
    // make sure that the transmit data register is empty
    while (!(pUSART3->SR & (1 << 7)))
        ;

    // write to transmit data register
    pUSART3->DR = (ch & 0xFF);
}
